version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - auth_service/.env
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
    environment:
      POSTGRES_DB: auth_service 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  # redis:
  #   image: redis:6
  #   ports:
  #     - "6379:6379"
  redis:
    image: redis:6
    ports:
      - "6381:6379" 

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A auth_service worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - auth_service/.env

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A auth_service beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - auth_service/.env

volumes:
  postgres_data:
